// src/layout/index.vue
<script setup lang="ts">
import { NLayout } from 'naive-ui'

import Header from './header/index.vue'
import Aside from './aside/index.vue'
import Main from './main/index.vue'
import Footer from './footer/index.vue'

</script>
<template>
  <NLayout>
    <div class="flex h-screen flex-col">
      <Header />
      <div class="flex flex-1">
        <Aside />
        <Main />
      </div>
      <Footer />
    </div>
  </NLayout>
</template>
<style>
</style>

// src/layout/index.tsx
import Header from '@/layout/Header'
import Aside from '@/layout/Aside'
import Main from '@/layout/Main'
import Footer from '@/layout/Footer'

export default function Shared() {
  return (
    <div
      className='flex h-screen w-screen'
    >
      <Aside />
      <div
        className='flex flex-1 flex-col'
      >
        <Header />
        <div
          className='flex-1'
        >
          <Main />
        </div>
        <Footer />
      </div>
    </div>
  )
}
